server:
  port: 8088
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: API_SERVER
          uri: lb://API-SERVER
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<path>.*),/$\{path}

